// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADEzZ3RVrfwiGo2EN3sMj2rLhmG2zBLyQ',
    appId: '1:69903938202:web:ce87a47b813302636ce523',
    messagingSenderId: '69903938202',
    projectId: 'appple-yonsei',
    authDomain: 'appple-yonsei.firebaseapp.com',
    storageBucket: 'appple-yonsei.appspot.com',
    measurementId: 'G-Z1CZWXWTM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoLf8PJF5xPvzkWaj0RN2lK-bl8ejafJc',
    appId: '1:69903938202:android:9f62c8167b27de016ce523',
    messagingSenderId: '69903938202',
    projectId: 'appple-yonsei',
    storageBucket: 'appple-yonsei.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXz9_fZCkA-2vxny-bqLg_AdV3g6GW6Hw',
    appId: '1:69903938202:ios:6fc86291c692cc716ce523',
    messagingSenderId: '69903938202',
    projectId: 'appple-yonsei',
    storageBucket: 'appple-yonsei.appspot.com',
    iosBundleId: 'com.example.airbandb',
  );
}
